### ISSUE TITLE
语言检测

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-bot#1]
当发现 issue title 里面出现中文时，自动回复建议使用英文讨论？

**Comment by benjycui** [comment]
按这个本地跑不起来啊 https://github.com/ant-design/ant-bot#development @yesmeck

**Comment by yesmeck** [comment]
https://github.com/dachev/node-cld

**Comment by monkindey** [comment]
> 当发现 issue title 里面出现中文时，自动回复建议使用英文讨论？

是否可以使用正则匹配中文来检测呢?
